<?php

/**
 * Implements hook_theme().
 **/

function liquid_theme($existing, $type, $theme, $path)
{

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'liquid-theme-hook' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'liquid-theme-hook',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'titles' => [],
      ],
    ],
  ];
}
